
insert into auths (auth_name) values ("admin");
insert into auths (auth_name) values ("user");
insert into auths (auth_name) values ("vip");

insert into levels (name) VALUES ("private");
insert into levels (name) VALUES ("public");


INSERT INTO countries (country_name, country_code) VALUES ('Andorra', 'AD');
INSERT INTO countries (country_name, country_code) VALUES ('United Arab Emirates', 'AE');
INSERT INTO countries (country_name, country_code) VALUES ('Afghanistan', 'AF');
INSERT INTO countries (country_name, country_code) VALUES ('Antigua & Barbuda', 'AG');
INSERT INTO countries (country_name, country_code) VALUES ('Anguilla', 'AI');
INSERT INTO countries (country_name, country_code) VALUES ('Albania', 'AL');
INSERT INTO countries (country_name, country_code) VALUES ('Armenia', 'AM');
INSERT INTO countries (country_name, country_code) VALUES ('Angola', 'AO');
INSERT INTO countries (country_name, country_code) VALUES ('Argentina', 'AR');
INSERT INTO countries (country_name, country_code) VALUES ('American Samoa', 'AS');
INSERT INTO countries (country_name, country_code) VALUES ('Austria', 'AT');
INSERT INTO countries (country_name, country_code) VALUES ('Australia', 'AU');
INSERT INTO countries (country_name, country_code) VALUES ('Aruba', 'AW');
INSERT INTO countries (country_name, country_code) VALUES ('Aland Islands', 'AX');
INSERT INTO countries (country_name, country_code) VALUES ('Azerbaijan', 'AZ');
INSERT INTO countries (country_name, country_code) VALUES ('Bosnia & Herzegovina', 'BA');
INSERT INTO countries (country_name, country_code) VALUES ('Barbados', 'BB');
INSERT INTO countries (country_name, country_code) VALUES ('Bangladesh', 'BD');
INSERT INTO countries (country_name, country_code) VALUES ('Belgium', 'BE');
INSERT INTO countries (country_name, country_code) VALUES ('Burkina Faso', 'BF');
INSERT INTO countries (country_name, country_code) VALUES ('Bulgaria', 'BG');
INSERT INTO countries (country_name, country_code) VALUES ('Bahrain', 'BH');
INSERT INTO countries (country_name, country_code) VALUES ('Burundi', 'BI');
INSERT INTO countries (country_name, country_code) VALUES ('Benin', 'BJ');
INSERT INTO countries (country_name, country_code) VALUES ('St. Barthélemy', 'BL');
INSERT INTO countries (country_name, country_code) VALUES ('Bermuda', 'BM');
INSERT INTO countries (country_name, country_code) VALUES ('Brunei', 'BN');
INSERT INTO countries (country_name, country_code) VALUES ('Bolivia', 'BO');
INSERT INTO countries (country_name, country_code) VALUES ('Brazil', 'BR');
INSERT INTO countries (country_name, country_code) VALUES ('Bahamas', 'BS');
INSERT INTO countries (country_name, country_code) VALUES ('Bhutan', 'BT');
INSERT INTO countries (country_name, country_code) VALUES ('Bouquet Island', 'BV');
INSERT INTO countries (country_name, country_code) VALUES ('Botswana', 'BW');
INSERT INTO countries (country_name, country_code) VALUES ('Belarus', 'BY');
INSERT INTO countries (country_name, country_code) VALUES ('Belize', 'BZ');
INSERT INTO countries (country_name, country_code) VALUES ('Canada', 'CA');
INSERT INTO countries (country_name, country_code) VALUES ('Cocos (Keeling) Islands', 'CC');
INSERT INTO countries (country_name, country_code) VALUES ('Congo - Kinshasa', 'CD');
INSERT INTO countries (country_name, country_code) VALUES ('Central African Republic', 'CF');
INSERT INTO countries (country_name, country_code) VALUES ('Congo - Brazzaville', 'CG');
INSERT INTO countries (country_name, country_code) VALUES ('Switzerland', 'CH');
INSERT INTO countries (country_name, country_code) VALUES ('Côte d’Ivoire', 'CI');
INSERT INTO countries (country_name, country_code) VALUES ('Cook Islands', 'CK');
INSERT INTO countries (country_name, country_code) VALUES ('Chile', 'CL');
INSERT INTO countries (country_name, country_code) VALUES ('Cameroon', 'CM');
INSERT INTO countries (country_name, country_code) VALUES ('China', 'CN');
INSERT INTO countries (country_name, country_code) VALUES ('Colombia', 'CO');
INSERT INTO countries (country_name, country_code) VALUES ('Costa Rica', 'CR');
INSERT INTO countries (country_name, country_code) VALUES ('Cuba', 'CU');
INSERT INTO countries (country_name, country_code) VALUES ('Cape Verde', 'CV');
INSERT INTO countries (country_name, country_code) VALUES ('Curaçao', 'CW');
INSERT INTO countries (country_name, country_code) VALUES ('Christmas Island', 'CX');
INSERT INTO countries (country_name, country_code) VALUES ('Cyprus', 'CY');
INSERT INTO countries (country_name, country_code) VALUES ('Czech Republic', 'CZ');
INSERT INTO countries (country_name, country_code) VALUES ('Germany', 'DE');
INSERT INTO countries (country_name, country_code) VALUES ('Djibouti', 'DJ');
INSERT INTO countries (country_name, country_code) VALUES ('Denmark', 'DK');
INSERT INTO countries (country_name, country_code) VALUES ('Dominica', 'DM');
INSERT INTO countries (country_name, country_code) VALUES ('Dominican Republic', 'DO');
INSERT INTO countries (country_name, country_code) VALUES ('Algeria', 'DZ');
INSERT INTO countries (country_name, country_code) VALUES ('Ecuador', 'EC');
INSERT INTO countries (country_name, country_code) VALUES ('Estonia', 'EE');
INSERT INTO countries (country_name, country_code) VALUES ('Egypt', 'EG');
INSERT INTO countries (country_name, country_code) VALUES ('Eritrea', 'ER');
INSERT INTO countries (country_name, country_code) VALUES ('Spain', 'ES');
INSERT INTO countries (country_name, country_code) VALUES ('Ethiopia', 'ET');
INSERT INTO countries (country_name, country_code) VALUES ('European Union', 'EU');
INSERT INTO countries (country_name, country_code) VALUES ('Finland', 'FI');
INSERT INTO countries (country_name, country_code) VALUES ('Fiji', 'FJ');
INSERT INTO countries (country_name, country_code) VALUES ('Falkland Islands', 'FK');
INSERT INTO countries (country_name, country_code) VALUES ('Micronesia', 'FM');
INSERT INTO countries (country_name, country_code) VALUES ('Faroe Islands', 'FO');
INSERT INTO countries (country_name, country_code) VALUES ('France', 'FR');
INSERT INTO countries (country_name, country_code) VALUES ('Gabon', 'GA');
INSERT INTO countries (country_name, country_code) VALUES ('United Kingdom', 'GB');
INSERT INTO countries (country_name, country_code) VALUES ('England', 'GB-ENG');
INSERT INTO countries (country_name, country_code) VALUES ('Northern Ireland', 'GB-NIR');
INSERT INTO countries (country_name, country_code) VALUES ('Scotland', 'GB-SCT');
INSERT INTO countries (country_name, country_code) VALUES ('Wales', 'GB-WLS');
INSERT INTO countries (country_name, country_code) VALUES ('Shetland', 'GB-ZET');
INSERT INTO countries (country_name, country_code) VALUES ('Grenada', 'GD');
INSERT INTO countries (country_name, country_code) VALUES ('Georgia', 'GE');
INSERT INTO countries (country_name, country_code) VALUES ('French Guiana', 'GF');
INSERT INTO countries (country_name, country_code) VALUES ('Guernsey', 'GG');
INSERT INTO countries (country_name, country_code) VALUES ('Ghana', 'GH');
INSERT INTO countries (country_name, country_code) VALUES ('Gibraltar', 'GI');
INSERT INTO countries (country_name, country_code) VALUES ('Greenland', 'GL');
INSERT INTO countries (country_name, country_code) VALUES ('Gambia', 'GM');
INSERT INTO countries (country_name, country_code) VALUES ('Guinea', 'GN');
INSERT INTO countries (country_name, country_code) VALUES ('Guadeloupe', 'GP');
INSERT INTO countries (country_name, country_code) VALUES ('Equatorial Guinea', 'GQ');
INSERT INTO countries (country_name, country_code) VALUES ('Greece', 'GR');
INSERT INTO countries (country_name, country_code) VALUES ('So. Georgia & So. Sandwich Isl.', 'GS');
INSERT INTO countries (country_name, country_code) VALUES ('Guatemala', 'GT');
INSERT INTO countries (country_name, country_code) VALUES ('Guam', 'GU');
INSERT INTO countries (country_name, country_code) VALUES ('Guinea-Bissau', 'GW');
INSERT INTO countries (country_name, country_code) VALUES ('Guyana', 'GY');
INSERT INTO countries (country_name, country_code) VALUES ('Hong Kong (China)', 'HK');
INSERT INTO countries (country_name, country_code) VALUES ('Heard & McDonald Islands', 'HM');
INSERT INTO countries (country_name, country_code) VALUES ('Honduras', 'HN');
INSERT INTO countries (country_name, country_code) VALUES ('Croatia', 'HR');
INSERT INTO countries (country_name, country_code) VALUES ('Haiti', 'HT');
INSERT INTO countries (country_name, country_code) VALUES ('Hungary', 'HU');
INSERT INTO countries (country_name, country_code) VALUES ('Indonesia', 'ID');
INSERT INTO countries (country_name, country_code) VALUES ('Ireland', 'IE');
INSERT INTO countries (country_name, country_code) VALUES ('Israel', 'IL');
INSERT INTO countries (country_name, country_code) VALUES ('Isle of Man', 'IM');
INSERT INTO countries (country_name, country_code) VALUES ('India', 'IN');
INSERT INTO countries (country_name, country_code) VALUES ('British Indian Ocean Territory', 'IO');
INSERT INTO countries (country_name, country_code) VALUES ('Iraq', 'IQ');
INSERT INTO countries (country_name, country_code) VALUES ('Iran', 'IR');
INSERT INTO countries (country_name, country_code) VALUES ('Iceland', 'IS');
INSERT INTO countries (country_name, country_code) VALUES ('Italy', 'IT');
INSERT INTO countries (country_name, country_code) VALUES ('Jersey', 'JE');
INSERT INTO countries (country_name, country_code) VALUES ('Jamaica', 'JM');
INSERT INTO countries (country_name, country_code) VALUES ('Jordan', 'JO');
INSERT INTO countries (country_name, country_code) VALUES ('Japan', 'JP');
INSERT INTO countries (country_name, country_code) VALUES ('Kenya', 'KE');
INSERT INTO countries (country_name, country_code) VALUES ('Kyrgyzstan', 'KG');
INSERT INTO countries (country_name, country_code) VALUES ('Cambodia', 'KH');
INSERT INTO countries (country_name, country_code) VALUES ('Kiribati', 'KI');
INSERT INTO countries (country_name, country_code) VALUES ('Comoros', 'KM');
INSERT INTO countries (country_name, country_code) VALUES ('St. Kitts & Nevis', 'KN');
INSERT INTO countries (country_name, country_code) VALUES ('North Korea', 'KP');
INSERT INTO countries (country_name, country_code) VALUES ('South Korea', 'KR');
INSERT INTO countries (country_name, country_code) VALUES ('Kuwait', 'KW');
INSERT INTO countries (country_name, country_code) VALUES ('Cayman Islands', 'KY');
INSERT INTO countries (country_name, country_code) VALUES ('Kazakhstan', 'KZ');
INSERT INTO countries (country_name, country_code) VALUES ('Laos', 'LA');
INSERT INTO countries (country_name, country_code) VALUES ('Lebanon', 'LB');
INSERT INTO countries (country_name, country_code) VALUES ('St. Lucia', 'LC');
INSERT INTO countries (country_name, country_code) VALUES ('Pride', 'LGBT');
INSERT INTO countries (country_name, country_code) VALUES ('Liechtenstein', 'LI');
INSERT INTO countries (country_name, country_code) VALUES ('Sri Lanka', 'LK');
INSERT INTO countries (country_name, country_code) VALUES ('Liberia', 'LR');
INSERT INTO countries (country_name, country_code) VALUES ('Lesotho', 'LS');
INSERT INTO countries (country_name, country_code) VALUES ('Lithuania', 'LT');
INSERT INTO countries (country_name, country_code) VALUES ('Luxembourg', 'LU');
INSERT INTO countries (country_name, country_code) VALUES ('Latvia', 'LV');
INSERT INTO countries (country_name, country_code) VALUES ('Libya', 'LY');
INSERT INTO countries (country_name, country_code) VALUES ('Morocco', 'MA');
INSERT INTO countries (country_name, country_code) VALUES ('Monaco', 'MC');
INSERT INTO countries (country_name, country_code) VALUES ('Moldova', 'MD');
INSERT INTO countries (country_name, country_code) VALUES ('Montenegro', 'ME');
INSERT INTO countries (country_name, country_code) VALUES ('St. Martin', 'MF');
INSERT INTO countries (country_name, country_code) VALUES ('Madagascar', 'MG');
INSERT INTO countries (country_name, country_code) VALUES ('Marshall Islands', 'MH');
INSERT INTO countries (country_name, country_code) VALUES ('Macedonia', 'MK');
INSERT INTO countries (country_name, country_code) VALUES ('Mali', 'ML');
INSERT INTO countries (country_name, country_code) VALUES ('Myanmar (Burma)', 'MM');
INSERT INTO countries (country_name, country_code) VALUES ('Mongolia', 'MN');
INSERT INTO countries (country_name, country_code) VALUES ('Macau (China)', 'MO');
INSERT INTO countries (country_name, country_code) VALUES ('Northern Mariana Islands', 'MP');
INSERT INTO countries (country_name, country_code) VALUES ('Martinique', 'MQ');
INSERT INTO countries (country_name, country_code) VALUES ('Mauritania', 'MR');
INSERT INTO countries (country_name, country_code) VALUES ('Montserrat', 'MS');
INSERT INTO countries (country_name, country_code) VALUES ('Malta', 'MT');
INSERT INTO countries (country_name, country_code) VALUES ('Mauritius', 'MU');
INSERT INTO countries (country_name, country_code) VALUES ('Maldives', 'MV');
INSERT INTO countries (country_name, country_code) VALUES ('Malawi', 'MW');
INSERT INTO countries (country_name, country_code) VALUES ('Mexico', 'MX');
INSERT INTO countries (country_name, country_code) VALUES ('Malaysia', 'MY');
INSERT INTO countries (country_name, country_code) VALUES ('Mozambique', 'MZ');
INSERT INTO countries (country_name, country_code) VALUES ('Namibia', 'NA');
INSERT INTO countries (country_name, country_code) VALUES ('New Caledonia', 'NC');
INSERT INTO countries (country_name, country_code) VALUES ('Niger', 'NE');
INSERT INTO countries (country_name, country_code) VALUES ('Norfolk Island', 'NF');
INSERT INTO countries (country_name, country_code) VALUES ('Nigeria', 'NG');
INSERT INTO countries (country_name, country_code) VALUES ('Nicaragua', 'NI');
INSERT INTO countries (country_name, country_code) VALUES ('Netherlands', 'NL');
INSERT INTO countries (country_name, country_code) VALUES ('Norway', 'NO');
INSERT INTO countries (country_name, country_code) VALUES ('Nepal', 'NP');
INSERT INTO countries (country_name, country_code) VALUES ('Nauru', 'NR');
INSERT INTO countries (country_name, country_code) VALUES ('Niue', 'NU');
INSERT INTO countries (country_name, country_code) VALUES ('New Zealand', 'NZ');
INSERT INTO countries (country_name, country_code) VALUES ('Oman', 'OM');
INSERT INTO countries (country_name, country_code) VALUES ('Panama', 'PA');
INSERT INTO countries (country_name, country_code) VALUES ('Peru', 'PE');
INSERT INTO countries (country_name, country_code) VALUES ('French Polynesia', 'PF');
INSERT INTO countries (country_name, country_code) VALUES ('Papua New Guinea', 'PG');
INSERT INTO countries (country_name, country_code) VALUES ('Philippines', 'PH');
INSERT INTO countries (country_name, country_code) VALUES ('Pakistan', 'PK');
INSERT INTO countries (country_name, country_code) VALUES ('Poland', 'PL');
INSERT INTO countries (country_name, country_code) VALUES ('St. Pierre & Miquelon', 'PM');
INSERT INTO countries (country_name, country_code) VALUES ('Pitcairn Islands', 'PN');
INSERT INTO countries (country_name, country_code) VALUES ('Puerto Rico', 'PR');
INSERT INTO countries (country_name, country_code) VALUES ('Palestinian Territories', 'PS');
INSERT INTO countries (country_name, country_code) VALUES ('Portugal', 'PT');
INSERT INTO countries (country_name, country_code) VALUES ('Palau', 'PW');
INSERT INTO countries (country_name, country_code) VALUES ('Paraguay', 'PY');
INSERT INTO countries (country_name, country_code) VALUES ('Qatar', 'QA');
INSERT INTO countries (country_name, country_code) VALUES ('Réunion', 'RE');
INSERT INTO countries (country_name, country_code) VALUES ('Romania', 'RO');
INSERT INTO countries (country_name, country_code) VALUES ('Serbia', 'RS');
INSERT INTO countries (country_name, country_code) VALUES ('Russia', 'RU');
INSERT INTO countries (country_name, country_code) VALUES ('Rwanda', 'RW');
INSERT INTO countries (country_name, country_code) VALUES ('Saudi Arabia', 'SA');
INSERT INTO countries (country_name, country_code) VALUES ('Solomon Islands', 'SB');
INSERT INTO countries (country_name, country_code) VALUES ('Seychelles', 'SC');
INSERT INTO countries (country_name, country_code) VALUES ('Sudan', 'SD');
INSERT INTO countries (country_name, country_code) VALUES ('Sweden', 'SE');
INSERT INTO countries (country_name, country_code) VALUES ('Singapore', 'SG');
INSERT INTO countries (country_name, country_code) VALUES ('St. Helena', 'SH');
INSERT INTO countries (country_name, country_code) VALUES ('Slovenia', 'SI');
INSERT INTO countries (country_name, country_code) VALUES ('Svalbard & Jan Mayen', 'SJ');
INSERT INTO countries (country_name, country_code) VALUES ('Slovakia', 'SK');
INSERT INTO countries (country_name, country_code) VALUES ('Sierra Leone', 'SL');
INSERT INTO countries (country_name, country_code) VALUES ('San Marino', 'SM');
INSERT INTO countries (country_name, country_code) VALUES ('Senegal', 'SN');
INSERT INTO countries (country_name, country_code) VALUES ('Somalia', 'SO');
INSERT INTO countries (country_name, country_code) VALUES ('Suriname', 'SR');
INSERT INTO countries (country_name, country_code) VALUES ('South Sudan', 'SS');
INSERT INTO countries (country_name, country_code) VALUES ('São Tomé & Príncipe', 'ST');
INSERT INTO countries (country_name, country_code) VALUES ('El Salvador', 'SV');
INSERT INTO countries (country_name, country_code) VALUES ('Sint Maarten', 'SX');
INSERT INTO countries (country_name, country_code) VALUES ('Syria', 'SY');
INSERT INTO countries (country_name, country_code) VALUES ('Swaziland', 'SZ');
INSERT INTO countries (country_name, country_code) VALUES ('Turks & Caicos Islands', 'TC');
INSERT INTO countries (country_name, country_code) VALUES ('Chad', 'TD');
INSERT INTO countries (country_name, country_code) VALUES ('French Southern Territories', 'TF');
INSERT INTO countries (country_name, country_code) VALUES ('Togo', 'TG');
INSERT INTO countries (country_name, country_code) VALUES ('Thailand', 'TH');
INSERT INTO countries (country_name, country_code) VALUES ('Tajikistan', 'TJ');
INSERT INTO countries (country_name, country_code) VALUES ('Tokelau', 'TK');
INSERT INTO countries (country_name, country_code) VALUES ('Timor-Leste', 'TL');
INSERT INTO countries (country_name, country_code) VALUES ('Turkmenistan', 'TM');
INSERT INTO countries (country_name, country_code) VALUES ('Tunisia', 'TN');
INSERT INTO countries (country_name, country_code) VALUES ('Tonga', 'TO');
INSERT INTO countries (country_name, country_code) VALUES ('Turkey', 'TR');
INSERT INTO countries (country_name, country_code) VALUES ('Trinidad & Tobago', 'TT');
INSERT INTO countries (country_name, country_code) VALUES ('Tuvalu', 'TV');
INSERT INTO countries (country_name, country_code) VALUES ('Taiwan', 'TW');
INSERT INTO countries (country_name, country_code) VALUES ('Tanzania', 'TZ');
INSERT INTO countries (country_name, country_code) VALUES ('Ukraine', 'UA');
INSERT INTO countries (country_name, country_code) VALUES ('Uganda', 'UG');
INSERT INTO countries (country_name, country_code) VALUES ('U.S. Outlying Islands', 'UM');
INSERT INTO countries (country_name, country_code) VALUES ('United States', 'US');
INSERT INTO countries (country_name, country_code) VALUES ('California', 'US-CA');
INSERT INTO countries (country_name, country_code) VALUES ('Uruguay', 'UY');
INSERT INTO countries (country_name, country_code) VALUES ('Uzbekistan', 'UZ');
INSERT INTO countries (country_name, country_code) VALUES ('Vatican City', 'VA');
INSERT INTO countries (country_name, country_code) VALUES ('St. Vincent & Grenadines', 'VC');
INSERT INTO countries (country_name, country_code) VALUES ('Venezuela', 'VE');
INSERT INTO countries (country_name, country_code) VALUES ('British Virgin Islands', 'VG');
INSERT INTO countries (country_name, country_code) VALUES ('U.S. Virgin Islands', 'VI');
INSERT INTO countries (country_name, country_code) VALUES ('Vietnam', 'VN');
INSERT INTO countries (country_name, country_code) VALUES ('Vanuatu', 'VU');
INSERT INTO countries (country_name, country_code) VALUES ('Wallis & Futuna', 'WF');
INSERT INTO countries (country_name, country_code) VALUES ('Samoa', 'WS');
INSERT INTO countries (country_name, country_code) VALUES ('Kosovo', 'XK');
INSERT INTO countries (country_name, country_code) VALUES ('Yemen', 'YE');
INSERT INTO countries (country_name, country_code) VALUES ('Mayotte', 'YT');
INSERT INTO countries (country_name, country_code) VALUES ('South Africa', 'ZA');
INSERT INTO countries (country_name, country_code) VALUES ('Zambia', 'ZM');
INSERT INTO countries (country_name, country_code) VALUES ('Zimbabwe', 'ZW');

insert into genders (gender_name) VALUES ("Femenino");
insert into genders (gender_name) VALUES ("Masculino");
insert into genders (gender_name) VALUES ("Otros");

insert into languages (language_name) VALUES ("Java");
insert into languages (language_name) VALUES ("JavaScript");
insert into languages (language_name) VALUES ("MySQL");
insert into languages (language_name) VALUES ("HTML");
insert into languages (language_name) VALUES ("PHP");
insert into languages (language_name) VALUES ("Python");
insert into languages (language_name) VALUES ("XML");
insert into languages (language_name) VALUES ("React");
insert into languages (language_name) VALUES ("NodeJs");
insert into languages (language_name) VALUES ("TypeScript");
insert into languages (language_name) VALUES ("CSS");
insert into languages (language_name) VALUES ("C");
insert into languages (language_name) VALUES ("Cpp");
insert into languages (language_name) VALUES ("Cs");
insert into languages (language_name) VALUES ("Swift");
insert into languages (language_name) VALUES ("Go");
insert into languages (language_name) VALUES ("Kotlin");
insert into languages (language_name) VALUES ("Rust");
insert into languages (language_name) VALUES ("MatLab");
insert into languages (language_name) VALUES ("R");
insert into languages (language_name) VALUES ("Perl");
insert into languages (language_name) VALUES ("Object-C");
insert into languages (language_name) VALUES ("Scala");
insert into languages (language_name) VALUES ("Haskell");
insert into languages (language_name) VALUES ("Lua");
insert into languages (language_name) VALUES ("Shell-script");
insert into languages (language_name) VALUES ("SQL");
insert into languages (language_name) VALUES ("Assembly");
insert into languages (language_name) VALUES ("Groovy");
insert into languages (language_name) VALUES ("Dart");
insert into languages (language_name) VALUES ("COBOL");
insert into languages (language_name) VALUES ("Fortran");
insert into languages (language_name) VALUES ("Lisp");
insert into languages (language_name) VALUES ("Prolog");
insert into languages (language_name) VALUES ("Ada");
insert into languages (language_name) VALUES ("Angular");
insert into languages (language_name) VALUES ("Spring");
insert into languages (language_name) VALUES ("Spring-Boot");
insert into languages (language_name) VALUES ("Flutter");
insert into languages (language_name) VALUES ("SASS");
insert into languages (language_name) VALUES ("MariaDB");
insert into languages (language_name) VALUES ("FireBase");
insert into languages (language_name) VALUES ("Azure");
insert into languages (language_name) VALUES ("AWS");
insert into languages (language_name) VALUES ("DJango");
insert into languages (language_name) VALUES ("Pascal");
insert into languages (language_name) VALUES ("Vue");
insert into languages (language_name) VALUES ("Ember");
insert into languages (language_name) VALUES ("Backbone");
insert into languages (language_name) VALUES ("Express");
insert into languages (language_name) VALUES ("Ruby-on-Rails");
insert into languages (language_name) VALUES ("Flask");
insert into languages (language_name) VALUES ("ASP.NET");
insert into languages (language_name) VALUES ("Meteor");
insert into languages (language_name) VALUES ("Xamarin");
insert into languages (language_name) VALUES ("Unity");
insert into languages (language_name) VALUES ("Unreal-Engine");
insert into languages (language_name) VALUES ("MongoDB");
insert into languages (language_name) VALUES ("PostgreSQL");
insert into languages (language_name) VALUES ("Oracle-Database");
insert into languages (language_name) VALUES ("SQLite");
insert into languages (language_name) VALUES ("Redis");
insert into languages (language_name) VALUES ("Elasticsearch");
insert into languages (language_name) VALUES ("Kafka");
insert into languages (language_name) VALUES ("RabbitMQ");
insert into languages (language_name) VALUES ("Docker");
insert into languages (language_name) VALUES ("Kubernetes");
insert into languages (language_name) VALUES ("Jenkins");
insert into languages (language_name) VALUES ("GitLab");
insert into languages (language_name) VALUES ("Puppet");
insert into languages (language_name) VALUES ("Grafana");
insert into languages (language_name) VALUES ("Prometheus");
insert into languages (language_name) VALUES ("Selenium");
insert into languages (language_name) VALUES ("JIRA");
insert into languages (language_name) VALUES ("Confluence");
insert into languages (language_name) VALUES ("Slack");
insert into languages (language_name) VALUES ("Trello");
insert into languages (language_name) VALUES ("AWS-Lambda");
insert into languages (language_name) VALUES ("Google-Cloud-Functions");
insert into languages (language_name) VALUES ("Heroku");
insert into languages (language_name) VALUES ("DigitalOcean");
insert into languages (language_name) VALUES ("Git");
insert into languages (language_name) VALUES ("GitHub");
insert into languages (language_name) VALUES ("Vercel");
insert into languages (language_name) VALUES ("Intellij");
insert into languages (language_name) VALUES ("Visual-Studio-Code");
insert into languages (language_name) VALUES ("Eclipse");
insert into languages (language_name) VALUES ("NetBeans");



insert into users (name ,last_name, age, email, username, created_at, gender_id, password, country_id ) VALUES ("David", "Vazquez", 24, "dave@gmail.com", "dave_u", "2023-05-01", 2,"$2a$12$NFXPYctXO6JefCHi7dYsMOholC5dErCxF/sLIi9LFb6fVgDsAu6cu",161);

insert into users (name ,last_name, age, email, username, created_at, gender_id, password, country_id ) VALUES ("Michelle", "Trejo", 24 , "michelle@hotmail.com", "Error404", "2023-06-05", 2,"$2a$12$lzR0QfWl9g5UdeItjtE6TudquUAmtYML0cPmUGDKTAC7Z32srABZW", 161);

insert into users (name ,last_name, age, email, username, created_at, gender_id, password, country_id ) VALUES ("Patricia", "Matias", 22 , "ale@hotmail.com", "Tenshik0", "2023-06-05", 1,"$2a$12$/XkkGUHopjHFPoRdLNuzxunXxwiZljy8XDEuuScBZo7vbCY2nfsuK", 161);

insert into users (name ,last_name, age, email, username, created_at, gender_id, password, country_id ) VALUES ("Fatima", "Moreno", 23 , "faty@hotmail.com", "Faty", "2023-06-05", 1,"$2a$12$r9HvkpewFiyFxIWrnbAnBeNlAFeSYNCI9tnXJmqlpInBBt1IBzyy2", 161);

insert into users (name ,last_name, age, email, username, created_at, gender_id, password, country_id ) VALUES ("Omar", "Michaca", 24 , "omar@hotmail.com", "OmarMV", "2023-06-05", 2,"$2a$12$Z1J/fVtf2oKYxaf7M2wyguoUN0ZHj84qx6WNixpTtHR2dsUJi8536", 161);

insert into users (name ,last_name, age, email, username, created_at, gender_id, password, country_id ) VALUES ("Alvaro", "Gonzalez", 24 , "alvaro@hotmail.com", "Alv", "2023-06-05", 1,"$2a$12$V1OZT.mkH9NfiILMWjT3peuPWO0GxIW05IA1FD71qxgkJ11s288bK", 161);

insert into users (name ,last_name, age, email, username, created_at, gender_id, password, country_id ) VALUES ("Sofi", "Gomez", 20 , "sofi@hotmail.com", "Sof_gm", "2023-06-05", 1,"$2a$12$f5Ggc9qCunnQbKkF.V1ERu0WZxvd6G.jVxjvEMGsCBEl8NFaxbsuu", 161);

INSERT INTO `profiles` (birthday, bio, img_user, github_username, linkedin_username, background_user,role, level_id, user_id) VALUES("1999-01-08", "Hello there", "https://avatars.githubusercontent.com/u/112228738?s=400&u=cb45f8d1845468aa78303654a5d70703f372e7fe&v=4", "Dave", "David Vazquez" , "https://images.pexels.com/photos/924824/pexels-photo-924824.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1","Fullstack Developer Java & React", 2,1);
INSERT INTO `profiles` (birthday, bio, img_user, github_username, linkedin_username, background_user,role, level_id, user_id) VALUES("1999-10-10", "Hi there!", "https://avatars.githubusercontent.com/u/92353536?v=4", "Error404", "Michelle Trejo","https://images.pexels.com/photos/9504092/pexels-photo-9504092.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1","Java Developer", 1,2);
INSERT INTO `profiles` (birthday, bio, img_user, github_username, linkedin_username, background_user,role, level_id, user_id) VALUES("1991-02-04", "Cuac", "https://avatars.githubusercontent.com/u/116323180?v=4", "Patito", "Patricia Matías", "https://images.pexels.com/photos/162140/duckling-birds-yellow-fluffy-162140.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1","Fullstack Developer", 1,3);
INSERT INTO `profiles` (birthday, bio, img_user, github_username, linkedin_username, background_user,role, level_id, user_id) VALUES("2000-11-03", "Hola!", "https://avatars.githubusercontent.com/u/129539914?v=4", "Faty", "Fatima Moreno","https://images.pexels.com/photos/1083807/pexels-photo-1083807.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1","Fullstack Trainee", 1,4);
INSERT INTO `profiles` (birthday, bio, img_user, github_username, linkedin_username, background_user,role, level_id, user_id) VALUES("1999-07-08", "Let's talk", "https://images.pexels.com/photos/8107906/pexels-photo-8107906.jpeg?auto=compress&cs=tinysrgb&w=1600", "OmarMV", "Omar Michaca","https://images.pexels.com/photos/2129796/pexels-photo-2129796.png?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1","Java Developer", 1,5);
INSERT INTO `profiles` (birthday, bio, img_user, github_username, linkedin_username, background_user,role, level_id, user_id) VALUES("1998-12-08", "Woo!", "https://images.pexels.com/photos/2389349/pexels-photo-2389349.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1", "Alv", "Alvaro Gonzalez","https://images.pexels.com/photos/1080953/pexels-photo-1080953.jpeg?auto=compress&cs=tinysrgb&w=1600","Web Developer Trainee", 1,6);
INSERT INTO `profiles` (birthday, bio, img_user, github_username, linkedin_username, background_user,role, level_id, user_id) VALUES("2003-12-08", "Holi!", "https://images.pexels.com/photos/8718387/pexels-photo-8718387.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1", "Sofi_gm", "Sofi Gomez","https://images.pexels.com/photos/3389729/pexels-photo-3389729.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1","Web Developer Trainee", 1,7);

INSERT INTO user_roles (user_id, auth_id) VALUES (1,1);
INSERT INTO user_roles (user_id, auth_id) VALUES (1,2);
INSERT INTO user_roles (user_id, auth_id) VALUES (1,3);

INSERT INTO user_roles (user_id, auth_id) VALUES (2,1);
INSERT INTO user_roles (user_id, auth_id) VALUES (2,2);
INSERT INTO user_roles (user_id, auth_id) VALUES (2,3);

INSERT INTO user_roles (user_id, auth_id) VALUES (3,1);
INSERT INTO user_roles (user_id, auth_id) VALUES (3,2);
INSERT INTO user_roles (user_id, auth_id) VALUES (3,3);

INSERT INTO user_roles (user_id, auth_id) VALUES (4,1);
INSERT INTO user_roles (user_id, auth_id) VALUES (4,2);
INSERT INTO user_roles (user_id, auth_id) VALUES (4,3);

INSERT INTO user_roles (user_id, auth_id) VALUES (5,1);
INSERT INTO user_roles (user_id, auth_id) VALUES (5,2);
INSERT INTO user_roles (user_id, auth_id) VALUES (5,3);

INSERT INTO user_roles (user_id, auth_id) VALUES (6,1);
INSERT INTO user_roles (user_id, auth_id) VALUES (6,2);
INSERT INTO user_roles (user_id, auth_id) VALUES (6,3);

INSERT INTO user_roles (user_id, auth_id) VALUES (7,1);
INSERT INTO user_roles (user_id, auth_id) VALUES (7,2);
INSERT INTO user_roles (user_id, auth_id) VALUES (7,3);





